In [ ]:
import numpy as np

# Array

Um array é um conjunto de dados que podem estar dispostos em dimensões diferentes.

Tipos de Arrays:
- ndarrays -> são arrays com N dimensões
- 1-D array - > possui apenas uma dimensão, comumente chamados de vetor (vector)
- 2-D array - > possui duas dimensões, comumente chamados de matriz (matrix)
- 3-D array - > possui três dimensões, comumente chamados de tensor




## Criando um array
**np.array ()**

In [ ]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr1)
print(type(arr1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


É possível criar um array de zeros: **np.zeros()**

In [ ]:
arr_zero = np.zeros((3,2,5)) # shape = (dimensao y, dimensao x, dimensao z), pode ser escrito também como (shape = (y,x,z))

print(arr_zero)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


Array de uns: **np.ones()**

In [ ]:
arr_um = np.ones((3,2,4))

print(arr_um)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Para criar um array vazio sem a inicialização de valores: **np.empty()**

Serão preenchidos com os valores existentes na memória naquele momento.

In [ ]:
arr_vazio = np.empty((3,2))

print(arr_vazio)

[[4.67861754e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


Para criar um array de um determinado intervalo: **np.arange()**

cria-se: np.arange([start,stop,step]) ou np.arange(stop)

Ele cria respeitando a posição, caso ela não seja respeitada é necessário passar no código item a item como:

np.arange(step = numero, start = numero, stop = numero)

In [ ]:
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr3 = np.arange(1,11)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr4 = np.arange(0, 11, 2)
print(arr4)

[ 0  2  4  6  8 10]


In [ ]:
arr5 = np.arange(step = 10, start = 100, stop = 500)
print(arr5)

[100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270
 280 290 300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450
 460 470 480 490]


É possível criar uma sequência de números uniformemente espaçados em um intervalo especificado: **np.linspace()**

- Útil para criar arrays numéricos com uma quantidade específica de elementos, distribuídos de forma linear entre dois valores.

Cria-se: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

* start: Valor inicial do intervalo.
* stop: Valor final do intervalo.
* num: Número de elementos na sequência (padrão é 50).
* endpoint: Se True, o valor final está incluído na sequência (padrão é True).
* retstep: Se True, retorna o espaçamento entre os valores (padrão é False).
* dtype: Tipo de dados dos elementos na sequência (padrão é None).
* axis: Eixo ao longo do qual os elementos são gerados (padrão é 0).

In [ ]:
arr_linear = np.linspace(0, 10, num = 20, endpoint = False)
print(arr_linear)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
arr_linear2 = np.linspace(10, 100, num = 5)
print(arr_linear2)

[ 10.   32.5  55.   77.5 100. ]


## Tamanhos de um array

* array.shape = para ver qual o formato do array
* array.size = para ver a quantidade total de dados dentro do array
* array.ndim = para ver a quantidade de dimensões do array

In [ ]:
arr_um = np.ones((3,2,4))
print(arr_um)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
print(arr_um.shape) # formato
print(arr_um.size) # total de dados
print(arr_um.ndim) # quantidade de dimensões

(3, 2, 4)
24
3


## Mudar o tamanho de um array
**np.reshape**

Este comando reorganiza os elementos do array para uma nova forma especificada, sem alterar os dados contidos nele. Por exemplo, você pode usar np.reshape para converter um array unidimensional em uma matriz bidimensional ou para alterar as dimensões de uma matriz existente.

In [ ]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
arr1_reshape = arr1.reshape(5,2)
print(arr1_reshape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## Ordenando elementos de um array
**np.sort()**

In [ ]:
arr6 = np.array([81, 7, 2, 25, 72, 15])
print(arr6)

[81  7  2 25 72 15]


In [ ]:
arr6_crescente = np.sort(arr6)
print(arr6_crescente)

[ 2  7 15 25 72 81]


In [ ]:
arr6_decrescente = np.sort(arr6)[::-1]
print(arr6_decrescente)

[81 72 25 15  7  2]


## Transformando vetor em matriz

* np.newaxis = para criar uma nova dimensão

In [ ]:
vetor = np.array([0,1,2,3,4,5])
print(vetor)
print(vetor.shape)
print(vetor.ndim)

[0 1 2 3 4 5]
(6,)
1


In [ ]:
vetor2 = vetor[np.newaxis,:]
print(vetor2)
print(vetor2.shape)
print(vetor2.ndim)

[[0 1 2 3 4 5]]
(1, 6)
2


In [ ]:
vetor3 = vetor[:, np.newaxis]
print(vetor3)
print(vetor3.shape)
print(vetor3.ndim)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)
2


## Acessando dados de um array

In [ ]:
vetor2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
print(vetor2[0][1])

1


In [ ]:
arr7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (arr7)
print('--------------')
menor_5 = arr7[arr7<5]
print(menor_5)
print('--------------')
par = arr7[arr7%2==0]
print(par)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[1 2 3 4]
--------------
[2 4 6 8]


## Concatenando arrays
**np.concatenate()**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

# Concatenando

c = np.concatenate((a,b))
d = np.concatenate((b,a))

In [ ]:
print(c)
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10  1  2  3  4  5]


# Operações com array

* soma = array.sum()
* valor mínimo = array.min()
* valor máximo = array.max()
* média = array.mean()

In [ ]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr7.sum())
print(arr7.min())
print(arr7.max())
print(arr7.mean())

45
1
9
5.0


## Gerando números aleatórios

In [ ]:
from numpy.random import default_rng

In [ ]:
rng = default_rng()

aleatorio = rng.integers(10, size = (2,4)) #rng.integers(numero_maximo, size =(linha,coluna))
print(aleatorio)

[[6 7 9 7]
 [6 9 5 7]]
